name: publish
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  OutputDirectory: ${{github.workspace}}/output
  ArtifactsDirectory: ${{github.workspace}}/artifacts

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@4
        with:
          node-version: "20"

      - name: Restore NPM Packages
        run: npm install

      - name: Test build
        run: npm run build
